### ISSUE TITLE
Trip cache grows slightly over iterations

### ISSUE THREAD

**Issue by F-I-D-O** [aicenter/agentpolis#22]
<a href="https://github.com/F-I-D-O"><img src="https://avatars2.githubusercontent.com/u/2853732?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [F-I-D-O](https://github.com/F-I-D-O)**
_Friday Mar 24, 2017 at 09:50 GMT_
_Originally opened as https://github.com/agents4its/agentpolis/issues/41_

----

**Comment by matalukes** [comment]
It is fixed on branch bug/trip_cache_grows - amod project.
