### ISSUE TITLE
TripsUtil vs PositionUtils

### ISSUE THREAD

**Issue by F-I-D-O** [aicenter/agentpolis#37]
<a href="https://github.com/schaemar"><img src="https://avatars0.githubusercontent.com/u/1151556?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [schaemar](https://github.com/schaemar)**
_Monday Jun 19, 2017 at 14:48 GMT_
_Originally opened as https://github.com/agents4its/agentpolis/issues/57_

----

Remove duplicated code, refactor

**Comment by F-I-D-O** [comment]
method getEdgeLength

**Comment by korytmar** [comment]
duplicated code in TripsUtil has no usage -> removed

**Comment by F-I-D-O** [comment]
solved
