### ISSUE TITLE
Remove VehicleTrip

### ISSUE THREAD

**Issue by F-I-D-O** [aicenter/agentpolis#40]
<a href="https://github.com/F-I-D-O"><img src="https://avatars2.githubusercontent.com/u/2853732?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [F-I-D-O](https://github.com/F-I-D-O)**
_Wednesday Jul 19, 2017 at 08:52 GMT_
_Originally opened as https://github.com/agents4its/agentpolis/issues/60_

----

**Comment by korytmar** [comment]
GraphTrip is abstract class (issue).

**Comment by F-I-D-O** [comment]
invalid
