### ISSUE TITLE
DefaultVisioInitializer is using projected coordinates

### ISSUE THREAD

**Issue by marekcuchy** [aicenter/agentpolis#83]
Why is DefaultVisioInitializer.initWindow() using projected coordinates to determine centroid?
```
public Point2d getDefaultLookAt() {
	GPSLocation centroid = Utils2D.getGraphCentroid(highwayNetwork.getNetwork());
	int centroidProjectionSRID = config.srid;
	GPSLocation centroidWGS84 = VisioPositionUtil.getWGS84PositionFromCustomProjection(centroid.getLatitudeProjected1E2(), centroid.getLongitudeProjected1E2(), centroidProjectionSRID);
	Point2d centerPoint = new Point2d(centroidWGS84.getLongitudeProjected(), centroidWGS84.getLatitudeProjected());
	return centerPoint;
}
```

It could just extract the centroid in GPS (WGS84) coordinates directly from the highwayNetwork and then convert it to mercator.

P.S.  getWGS84PositionFromCustomProjection() function has a bad name. It returns more than WGS84 coodinates - it adds mercator coordinates which, btw, is the main reason why the function is called here. 

P.P.S. it is the only usage  of 'agentpolisConfig.srid' outside  StandardAgentPolisModule (version 5.1.1). Also `bindConstant().annotatedWith(Names.named("mapSrid")).to(agentpolisConfig.srid)` is "used" only in NearestElementUtils (it is just unused parameter in constructor). We should consider to remove it - is it used in other modules based on agentpolis?

**Comment by F-I-D-O** [comment]
PPS added as a separate issue.

**Comment by F-I-D-O** [comment]
Why is it bad to compute the centroid from projected coordinates?

**Comment by marekcuchy** [comment]
It is not necessary to use the projected coordinates. The main location information is the standard GPS coordinates and the projected coordinates should be used only when it is necessary, e.g. for performance reason (calculating distance or nearest nodes).

This implementation unnecessarily adds dependency to a construct that brings quite big maintenance issues caused by the conversion (the deployment can be quite troublesome because of the library used for the conversion).

**Comment by marekcuchy** [comment]
fixed
